url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Brian Hwang Golf
email: bhwang@pga.com
description: "Brian Hwang Golf - Professional Instruction"


# Team names, titles and social links
people:
- name: Brian Hwang
  pic: brian_headshot
  position: Instructor
  social:
    - title: instagram
      url: http://instagram.com/brianhwanggolf
    # - title: facebook
    #   url: #
    # - title: stack-overflow
    #   url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/brianhwanggolf

# Postal address (add as many lines as necessary)
address:
  - line: Pine Hollow Country Club
  - line: 6601 Northern Blvd
  - line: East Norwich, NY 11732

# Build settings
markdown: kramdown
permalink: pretty